version: 0.2
phases:
  install:
    runtime-versions:
       docker: 19
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - echo logging to ecr
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - echo starting build on 'date'
      - cd ./
      - docker build -t thecoolroom .
      - docker tag thecoolroom:latest 386312811183.dkr.ecr.ap-southeast-2.amazonaws.com/thecoolroom:latest
  post_build:
    commands:
      - echo build completed on 'date'
      - echo pushing to repo
      - docker push 386312811183.dkr.ecr.ap-southeast-2.amazonaws.com/thecoolroom:latest
      - echo Writing definitions file...
      - printf '[{"name":"TheCoolRoom-container","imageUri":"%s"}]' 386312811183.dkr.ecr.ap-southeast-2.amazonaws.com/thecoolroom:latest > TheCoolRoomtaskdefinition.json
artifacts:
  files: TheCoolRoomtaskdefinition.json
