branch-defaults:
  default:
    environment: TheCoolRoom-dev
    group_suffix: null
global:
  application_name: TheCoolRoom
  branch: null
  default_ec2_keyname: aws-eb-syd
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
